[package]
name = "cam"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = { version = "0.93", default-features = false, features = ["imgproc", "imgcodecs", "highgui", "videoio","dnn"] }
tokio = { version = "1", features = ["full"] }
ort = { version = "2.0.0-rc.10", features = ["ndarray"] }
ndarray = "0.16"
bytes = "1"
warp = "0.3"
async-stream = "0.3"
log = "0.4"
env_logger = "0.11"
anyhow = "1"
